apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cube-api-efs-claim-prd
  namespace: cube-prd
spec:
  volumeName: cube-api-efs-prd
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 6Gi
