apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: key-pair-secrets
  namespace: cube
spec:
  provider: aws

  secretObjects:
    - secretName: snowflake-cube-pk
      type: Opaque
      data:
        - objectName: vendor_source_SNOWFLAKE_PRIVATE_KEY_PASSWORD
          key: vendor_source_SNOWFLAKE_PRIVATE_KEY_PASSWORD
        - objectName: vendor_source_SNOWFLAKE_PRIVATE_KEY_PATH
          key: vendor_source_SNOWFLAKE_PRIVATE_KEY_PATH

  parameters:
    objects: |
      - objectName: "SNOWFLAKE_CUBE/PRIVATE_KEY"
        objectType: "secretsmanager"
      - objectName: "SNOWFLAKE_CUBE/PRIVATE_KEY_INFO"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: vendor_source_SNOWFLAKE_PRIVATE_KEY_PASSWORD
          - path: path
            objectAlias: vendor_source_SNOWFLAKE_PRIVATE_KEY_PATH