apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cube-secrets
  namespace: cube
spec:
  provider: aws

  secretObjects:
    - secretName: cube-api-secrets
      type: Opaque
      data:
        - objectName: vendor_source_SNOWFLAKE_USER
          key: vendor_source_SNOWFLAKE_USER
        - objectName: vendor_source_SNOWFLAKE_PASSWORD
          key: vendor_source_SNOWFLAKE_PASSWORD
        - objectName: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
          key: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
        - objectName: vendor_source_SNOWFLAKE_ONLY_REGION
          key: vendor_source_SNOWFLAKE_ONLY_REGION
        - objectName: vendor_source_SNOWFLAKE_WAREHOUSE
          key: vendor_source_SNOWFLAKE_WAREHOUSE
        - objectName: vendor_source_SNOWFLAKE_DATABASE
          key: vendor_source_SNOWFLAKE_DATABASE
        - objectName: vendor_source_SNOWFLAKE_SCHEMA
          key: vendor_source_SNOWFLAKE_SCHEMA
        - objectName: IOT_POSTGRES_USERNAME
          key: IOT_POSTGRES_USERNAME
        - objectName: IOT_POSTGRES_PASSWORD
          key: IOT_POSTGRES_PASSWORD
        - objectName: IOT_POSTGRES_PORT
          key: IOT_POSTGRES_PORT
        - objectName: IOT_POSTGRES_HOST
          key: IOT_POSTGRES_HOST
        - objectName: IOT_POSTGRES_SCHEMA
          key: IOT_POSTGRES_SCHEMA
        - objectName: IOT_POSTGRES_DATABASE
          key: IOT_POSTGRES_DATABASE
        - objectName: PMS_SNOWFLAKE_USER
          key: PMS_SNOWFLAKE_USER
        - objectName: PMS_SNOWFLAKE_PASSWORD
          key: PMS_SNOWFLAKE_PASSWORD
        - objectName: PMS_SNOWFLAKE_ACCOUNT
          key: PMS_SNOWFLAKE_ACCOUNT
        - objectName: PMS_SNOWFLAKE_REGION
          key: PMS_SNOWFLAKE_REGION
        - objectName: PMS_SNOWFLAKE_WAREHOUSE
          key: PMS_SNOWFLAKE_WAREHOUSE
        - objectName: PMS_SNOWFLAKE_DATABASE
          key: PMS_SNOWFLAKE_DATABASE
        - objectName: IOT_SNOWFLAKE_USER
          key: IOT_SNOWFLAKE_USER
        - objectName: IOT_SNOWFLAKE_PASSWORD
          key: IOT_SNOWFLAKE_PASSWORD
        - objectName: IOT_SNOWFLAKE_ACCOUNT
          key: IOT_SNOWFLAKE_ACCOUNT
        - objectName: IOT_SNOWFLAKE_REGION
          key: IOT_SNOWFLAKE_REGION
        - objectName: IOT_SNOWFLAKE_WAREHOUSE
          key: IOT_SNOWFLAKE_WAREHOUSE
        - objectName: IOT_SNOWFLAKE_DATABASE
          key: IOT_SNOWFLAKE_DATABASE
        - objectName: IOT_SNOWFLAKE_SCHEMA
          key: IOT_SNOWFLAKE_SCHEMA
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_USER
          key: GOOGLE_ANALYTICS_SNOWFLAKE_USER
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_PASSWORD
          key: GOOGLE_ANALYTICS_SNOWFLAKE_PASSWORD
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
          key: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
          key: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
          key: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
          key: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
          key: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
        - objectName: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE
          key: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE

  parameters:
    objects: |
      - objectName: "SNOWFLAKE_CUBE"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: vendor_source_SNOWFLAKE_USER
          - path: password
            objectAlias: vendor_source_SNOWFLAKE_PASSWORD
          - path: account
            objectAlias: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
          - path: region
            objectAlias: vendor_source_SNOWFLAKE_ONLY_REGION
          - path: warehouse
            objectAlias: vendor_source_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: vendor_source_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: vendor_source_SNOWFLAKE_SCHEMA
      - objectName: "RDS_IOT_AIRBYTE_SVC"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: IOT_POSTGRES_USERNAME
          - path: password
            objectAlias: IOT_POSTGRES_PASSWORD
          - path: port
            objectAlias: IOT_POSTGRES_PORT
          - path: hostname
            objectAlias: IOT_POSTGRES_HOST
          - path: schema
            objectAlias: IOT_POSTGRES_SCHEMA
          - path: dbname
            objectAlias: IOT_POSTGRES_DATABASE
      - objectName: "SNOWFLAKE_PMS"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: PMS_SNOWFLAKE_USER
          - path: password
            objectAlias: PMS_SNOWFLAKE_PASSWORD
          - path: account
            objectAlias: PMS_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: PMS_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: PMS_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: PMS_SNOWFLAKE_DATABASE
      - objectName: "SNOWFLAKE_IOT"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: IOT_SNOWFLAKE_USER
          - path: password
            objectAlias: IOT_SNOWFLAKE_PASSWORD
          - path: account
            objectAlias: IOT_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: IOT_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: IOT_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: IOT_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: IOT_SNOWFLAKE_SCHEMA
      - objectName: "SNOWFLAKE_WEB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_USER
          - path: password
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_PASSWORD
          - path: account
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
          - path: role
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE