apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: key-pair-secrets
  namespace: cube
spec:
  parameters:
    objects: |
      - objectName: "company/reporting/prd/snowflake/cube/private-key"
        objectType: "secretsmanager"
  provider: aws
