apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cube-secrets
  namespace: cube
spec:
  parameters:
    objects: |
      - objectName: "company/reporting/prd/snowflake/cube"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: CUBE_SNOWFLAKE_USER
          - path: only_account
            objectAlias: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
          - path: only_region
            objectAlias: vendor_source_SNOWFLAKE_ONLY_REGION
          - path: warehouse
            objectAlias: vendor_source_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: vendor_source_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: vendor_source_SNOWFLAKE_SCHEMA
          - path: role
            objectAlias: vendor_source_SNOWFLAKE_ROLE
      - objectName: "company/reporting/prd/iot/airbyte"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: IOT_POSTGRES_USERNAME
          - path: password
            objectAlias: IOT_POSTGRES_PASSWORD
          - path: port
            objectAlias: IOT_POSTGRES_PORT
          - path: host
            objectAlias: IOT_POSTGRES_HOST
          - path: schema
            objectAlias: IOT_POSTGRES_SCHEMA
          - path: database
            objectAlias: IOT_POSTGRES_DATABASE
      - objectName: "company/reporting/prd/snowflake/pms"
        objectType: "secretsmanager"
        jmesPath:
          - path: account
            objectAlias: PMS_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: PMS_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: PMS_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: PMS_SNOWFLAKE_DATABASE
          - path: role
            objectAlias: PMS_SNOWFLAKE_ROLE
      - objectName: "company/reporting/prd/snowflake/iot"
        objectType: "secretsmanager"
        jmesPath:
          - path: account
            objectAlias: IOT_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: IOT_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: IOT_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: IOT_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: IOT_SNOWFLAKE_SCHEMA
          - path: role
            objectAlias: IOT_SNOWFLAKE_ROLE
      - objectName: "company/reporting/prd/snowflake/web"
        objectType: "secretsmanager"
        jmesPath:
          - path: account
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
          - path: region
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
          - path: warehouse
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
          - path: database
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
          - path: schema
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
          - path: role
            objectAlias: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE
  provider: aws
  secretObjects:
  - data:
    - key: CUBE_SNOWFLAKE_USER
      objectName: CUBE_SNOWFLAKE_USER
    - key: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
      objectName: vendor_source_SNOWFLAKE_ONLY_ACCOUNT
    - key: vendor_source_SNOWFLAKE_ONLY_REGION
      objectName: vendor_source_SNOWFLAKE_ONLY_REGION
    - key: vendor_source_SNOWFLAKE_WAREHOUSE
      objectName: vendor_source_SNOWFLAKE_WAREHOUSE
    - key: vendor_source_SNOWFLAKE_DATABASE
      objectName: vendor_source_SNOWFLAKE_DATABASE
    - key: vendor_source_SNOWFLAKE_SCHEMA
      objectName: vendor_source_SNOWFLAKE_SCHEMA
    - key: vendor_source_SNOWFLAKE_ROLE
      objectName: vendor_source_SNOWFLAKE_ROLE
    - key: IOT_POSTGRES_USERNAME
      objectName: IOT_POSTGRES_USERNAME
    - key: IOT_POSTGRES_PASSWORD
      objectName: IOT_POSTGRES_PASSWORD
    - key: IOT_POSTGRES_PORT
      objectName: IOT_POSTGRES_PORT
    - key: IOT_POSTGRES_HOST
      objectName: IOT_POSTGRES_HOST
    - key: IOT_POSTGRES_SCHEMA
      objectName: IOT_POSTGRES_SCHEMA
    - key: IOT_POSTGRES_DATABASE
      objectName: IOT_POSTGRES_DATABASE
    - key: PMS_SNOWFLAKE_ACCOUNT
      objectName: PMS_SNOWFLAKE_ACCOUNT
    - key: PMS_SNOWFLAKE_REGION
      objectName: PMS_SNOWFLAKE_REGION
    - key: PMS_SNOWFLAKE_WAREHOUSE
      objectName: PMS_SNOWFLAKE_WAREHOUSE
    - key: PMS_SNOWFLAKE_DATABASE
      objectName: PMS_SNOWFLAKE_DATABASE
    - key: PMS_SNOWFLAKE_ROLE
      objectName: PMS_SNOWFLAKE_ROLE
    - key: IOT_SNOWFLAKE_ACCOUNT
      objectName: IOT_SNOWFLAKE_ACCOUNT
    - key: IOT_SNOWFLAKE_REGION
      objectName: IOT_SNOWFLAKE_REGION
    - key: IOT_SNOWFLAKE_WAREHOUSE
      objectName: IOT_SNOWFLAKE_WAREHOUSE
    - key: IOT_SNOWFLAKE_DATABASE
      objectName: IOT_SNOWFLAKE_DATABASE
    - key: IOT_SNOWFLAKE_SCHEMA
      objectName: IOT_SNOWFLAKE_SCHEMA
    - key: IOT_SNOWFLAKE_ROLE
      objectName: IOT_SNOWFLAKE_ROLE
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_ACCOUNT
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_REGION
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_WAREHOUSE
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_DATABASE
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_SCHEMA
    - key: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE
      objectName: GOOGLE_ANALYTICS_SNOWFLAKE_ROLE
    secretName: cube-api-secrets
    type: Opaque